.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CHANGENAME" "1" "December 2014" "" ""
.
.SH "NAME"
\fBchangename\fR \- change the name of a Terminal window
.
.SH "SYNOPSIS"
\fBchangename\fR \fIname\fR
.
.br
\fBchangename alias\fR \fIalias\fR [\fIdirectory\fR]
.
.br
\fBchangename alias\fR (\fB\-g\fR|\fB\-\-get\fR) (\fIalias\fR|\fIdirectory\fR)
.
.br
\fBchangename alias\fR (\fB\-r\fR|\fB\-\-rename\fR) \fIfrom\fR \fIto\fR
.
.br
\fBchangename aliases\fR
.
.br
\fBchangename unalias\fR \fIalias\fR
.
.br
\fBchangename\fR [(\fB\-r\fR|\fB\-\-reset\fR)]
.
.br
\fBchangename\fR [(\fB\-h\fR|\fB\-\-help\fR)]
.
.br
\fBchangename\fR [(\fB\-d\fR|\fB\-\-directory\fR)] [(\fB\-a\fR|\fB\-\-use\-alias\fR)]
.
.SH "DESCRIPTION"
\fBchangename\fR changes the name of a Terminal window\. Useful when running scripts or when multiple Terminal window are open\.
.
.SH "OPTIONS"
.
.TP
\fIname\fR
Set the current window\'s title to \fIname\fR\.
.
.TP
\fBalias\fR \fIalias\fR [\fIdirectory\fR]
Create an alias for a directory\. If no directory is supplied, the working directory is used\.
.
.TP
\fB\-g\fR|\fB\-\-get\fR (\fIalias\fR|\fIdirectory\fR)
Switches \fBalias\fR to get mode\. The input can be either an \fIalias\fR or a \fIdirectory\fR and the matching value for an alias definition is printed, if any\.
.
.TP
\fB\-r\fR|\fB\-\-rename\fR \fIfrom\fR \fIto\fR
Switches \fBalias\fR to rename mode\. The alias \fIfrom\fR is renamed to \fIto\fR\.

.
.TP
\fBaliases\fR
Print existing alias definitions\.
.
.TP
\fBunalias\fR \fIalias\fR
Delete an alias definition\.
.
.TP
\fB\-r\fR|\fB\-\-reset\fR
Reset the current window\'s title\.
.
.TP
\fB\-h\fR|\fB\-\-help\fR
Display man page\.
.
.TP
\fB\-d\fR|\fB\-\-directory\fR
Use the current directory\'s name\.
.
.TP
\fB\-a\fR|\fB\-\-use\-alias\fR
Name the window according to the working directory\'s alias\.

