.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CHANGENAME" "1" "November 2014" "" ""
.
.SH "NAME"
\fBchangename\fR \- change the name of a Terminal window
.
.SH "SYNOPSIS"
\fBchangename\fR \fIname\fR
.
.br
\fBchangename\fR [(\fB\-r\fR|\fB\-\-reset\fR)]
.
.br
\fBchangename\fR [(\fB\-h\fR|\fB\-\-help\fR)]
.
.br
\fBchangename\fR [(\fB\-d\fR|\fB\-\-directory\fR)]
.
.SH "DESCRIPTION"
\fBchangename\fR changes the name of a Terminal window\. Useful when running scripts or when multiple Terminal window are open\.
.
.SH "OPTIONS"
.
.TP
\fIname\fR
Set the current window\'s title to \fIname\fR\.
.
.TP
\fB\-r\fR|\fB\-\-reset\fR
Reset the current window\'s title\.
.
.TP
\fB\-h\fR|\fB\-\-help\fR
Display man page\.
.
.TP
\fB\-d\fR|\fB\-\-directory\fR
Use the current directory\'s name\.

