.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "COLORTEXT" "1" "November 2014" "" ""
.
.SH "NAME"
\fBcolortext\fR \- echo colored text
.
.SH "SYNOPSIS"
\fBcolortext\fR \fIcolor\fR \fItext\fR
.
.br
\fBcolortext\fR [\fB\-c\fR|\fB\-\-colors\fR]
.
.br
\fBcolortext\fR [\fB\-e\fR|\fB\-\-examples\fR]
.
.br
\fBcolortext\fR [\fB\-h\fR|\fB\-\-help\fR]
.
.SH "DESCRIPTION"
\fBcolortext\fR outputs text in a given color\.
.
.SH "OPTIONS"
.
.TP
\fIcolor\fR
The color to use when printing the text\. It must be contained in the list from \fBcolortext\fR ( [\fB\-c\fR|\fB\-\-colors\fR] | [\fB\-e\fR|\fB\-\-examples\fR] )
.
.TP
\fB\-c\fR|\fB\-\-colors\fR
Print a list of available colors without coloring\.
.
.TP
\fB\-e\fR|\fB\-\-examples\fR
Print a list of available colors in their respective color\.
.
.TP
\fB\-h\fR|\fB\-\-help\fR
Display man page\.

